### ISSUE TITLE
! LaTeX Error: File `minimalist-default.sty' not found.

### ISSUE THREAD

**Issue by Clark-Young** [Jinwen-XU/jwjournal#3]
I try to use the template, but it doesn't work now. The error message is 

> ! LaTeX Error: File `minimalist-default.sty' not found.
 
I'm sure that minimalist package is installed in my PC.

**Comment by Clark-Young** [comment]
The file I compile is just the demo file, without any change.

**Comment by Jinwen-XU** [comment]
Thank you for reporting this!

It is almost surprising that I didn't realize this issue for such a long time. The problem has been existed for more than two months, and is due to the fact that I forgot to add the file `minimalist-default.sty` to my script generating the `.zip` file to be uploaded to CTAN. This has been corrected and within the next 48 hours you should be able to get an update for the package `minimalist` (very likely to have the version number `2023-09-27`) with the file `minimalist-default.sty` properly included. My apologize for the inconvenience caused.

Having a nice day, and if you encounter any further issues, feel free to continue the discussion here or to open a new channel.
